name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive .
      - run: black --check . || true
      - run: codespell
      - run: flake8 . --count --max-complexity=10 --max-line-length=88 --show-source --statistics
      - run: isort --check-only .
      - run: |
          pip install setuptools --editable . || true
          mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
